name: pm-world-clock
version: 0.0.1
summary: PM World Clock
description: Shows current AQI for locations across the globe

confinement: classic
base: core18
grade: stable

architectures:
  - build-on: amd64
    run-on: armhf

slots:
  dbus-pm-world-clock: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: com.example.pm_world_clock # adjust accordingly to your app name and
    
apps:
  pm-world-clock:
    command: pm_world_clock
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - dbus-pm-world-clock
parts:
  super-cool-app:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application